config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  use_doorkeeper
  devise_for :users, controllers: { omniauth_callbacks: 'omniauth_callbacks' }
  root to: 'questions#index'

  get :search, to: 'search#index'

  concern :votable do
    member do
      patch 'set_like'
      patch 'set_dislike'
      patch 'cancel_vote'
    end
  end

  concern :commentable do
    resources :comments, only: [:create, :update, :destroy], shallow: true
  end

  resources :questions, concerns: [:votable, :commentable] do
    resources :answers, shallow: true, concerns: [:votable, :commentable], only: [:create, :update, :destroy] do
      member do
        patch :set_best
      end
    end

    resources :subscriptions, only: [:create, :destroy], shallow: true
  end

  resources :attachments, only: :destroy

  mount ActionCable.server => '/cable'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  namespace :api do
    namespace :v1 do
      resources :profiles, only: :index do
        get :me, on: :collection
      end

      resources :questions, only: [:index, :show, :create] do
        resources :answers, only: [:index, :show, :create], shallow: true
      end
    end
  end
end

app/models/question.rb
class Question < ApplicationRecord
  include Attachable
  include Votable
  include Commentable

  belongs_to :user
  has_many :answers, dependent: :destroy
  has_many :subscriptions, dependent: :destroy
  has_many :subscribers, through: :subscriptions, source: :user

  validates :title, :body, presence: true

  scope :by_last_day, -> { where('created_at >= ?', 1.day.ago) }

  after_create_commit :subscribe_author

  private

  def subscribe_author
    subscriptions.create(user: user)
  end
end

app/controllers/api/v1/questions_controller.rb
class Api::V1::QuestionsController < Api::V1::BaseController
  before_action :load_question, only: :show

  authorize_resource

  def index
    @questions = Question.all
    respond_with @questions
  end

  def show
    respond_with @question
  end

  def create
    respond_with(@question = current_resource_owner.questions.create(question_params))
  end

  private

  def load_question
    @question = Question.find(params[:id])
  end

  def question_params
    params.require(:question).permit(:title, :body)
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  include Voted

  before_action :authenticate_user!, except: [:index, :show]
  before_action :load_question, only: [:show, :update, :destroy]
  before_action :load_subscription, only: [:show, :update]
  before_action :build_answer, only: :show
  after_action :publish_question, only: :create

  respond_to :html, :js

  authorize_resource

  def index
    respond_with(@questions = Question.all)
  end

  def show
    respond_with @question
  end

  def new
    respond_with(@question = current_user.questions.new)
  end

  def create
    respond_with(@question = current_user.questions.create(question_params))
  end

  def update
    @question.update(question_params)
    respond_with @question
  end

  def destroy
    respond_with(@question.destroy)
  end

  private

  def load_question
    @question = Question.find(params[:id])
    gon.question_id = @question.id
    gon.question_user_id = @question.user_id
  end

  def load_subscription
    @subscription = @question.subscriptions.find_by(user: current_user)
  end

  def question_params
    params.require(:question).permit(:title, :body, attachments_attributes: [:file, :id, :_destroy])
  end

  def build_answer
    @answer = @question.answers.new
  end

  def publish_question
    return if @question.errors.any?
    ActionCable.server.broadcast(
      'questions',
      ApplicationController.render(
        partial: 'questions/questions_item',
        locals: { question: @question }
      )
    )
  end
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/questions/_question.html.slim
.question
  h3= @question.title
  p= @question.body

  - if @question.attachments.any?
    .question_attachments
      = render 'attachments/list', resource: @question

  .question_rating
    = render 'votes/rating', resource: @question

  - if can? :update, @question
    => link_to 'Edit', '', class: 'edit-question-link'
    = form_for question, remote: true do |f|
      span.errors
      p= f.label :title
      p= f.text_field :title
      p= f.label :body
      p= f.text_area :body
      p= f.submit 'Save'
  - if can? :destroy, @question
    = link_to 'Delete', question_path(@question), method: :delete, data: { confirm: 'Are you sure?' }

  - if can?(:create, Subscription) || can?(:destroy, @subscription)
    .subscription
      - if current_user.subscribed?(@question)
        = link_to 'Unsubscribe', subscription_path(@subscription), method: :delete, remote: true, class: 'unsubscribe'
      - else
        = link_to 'Subscribe', question_subscriptions_path(@question), method: :post, remote: true, class: 'subscribe'

app/views/questions/_questions_item.html.slim
p
  = link_to question.title, question_path(question)
  br
  => question.body
  = "rating #{question.rating}"

app/views/questions/index.html.slim
h1 Questions list
.questions_list
  - cache collection_cache_key_for(:question) do
    - @questions.each do |q|
      = render 'questions_item', question: q

- if can? :create, Question
  p= link_to 'Ask question', new_question_path

app/views/questions/new.html.slim
= render partial: 'shared/errors', locals: { model: @question }

= form_for @question do |f|
  p= f.label :title
  p= f.text_field :title
  p= f.label :body
  p= f.text_area :body
  p Attachments:
  .attachments
    = f.fields_for :attachments, @question.attachments.new do |a|
      = render 'attachments/fields', f: a
      = link_to_add_association 'Attach file', f, :attachments, partial: 'attachments/fields'
  p= f.submit 'Create'

app/views/questions/show.html.slim
- cache @question do
  = render @question

  .question_comments
    - if can? :create, Comment
      = link_to 'Add comment', '', class: 'add-comment-link', data: {resource_id: @question.id, resource_type: 'question'}
      = render 'comments/form', resource: @question

    - if @question.comments.size > 1
      h4= 'Comments:'
      = render @question.comments

  - if @question.answers.any?
    h3= 'Answers:'
    .answers
      = render @question.answers

- if can? :create, Answer
  = render 'answers/form'

app/views/questions/update.js.erb
<% if @question&.errors.present? %>
  errors = $('form.edit_question').find('.errors');
  errors.html('<%= j render partial: 'shared/errors', locals: { model: @question } %>');
<% else %>
  $('.question').html('<%= j render @question %>');
<% end %>