config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  use_doorkeeper
  devise_for :users, controllers: { omniauth_callbacks: 'omniauth_callbacks' }
  root to: 'questions#index'

  get :search, to: 'search#index'

  concern :votable do
    member do
      patch 'set_like'
      patch 'set_dislike'
      patch 'cancel_vote'
    end
  end

  concern :commentable do
    resources :comments, only: [:create, :update, :destroy], shallow: true
  end

  resources :questions, concerns: [:votable, :commentable] do
    resources :answers, shallow: true, concerns: [:votable, :commentable], only: [:create, :update, :destroy] do
      member do
        patch :set_best
      end
    end

    resources :subscriptions, only: [:create, :destroy], shallow: true
  end

  resources :attachments, only: :destroy

  mount ActionCable.server => '/cable'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  namespace :api do
    namespace :v1 do
      resources :profiles, only: :index do
        get :me, on: :collection
      end

      resources :questions, only: [:index, :show, :create] do
        resources :answers, only: [:index, :show, :create], shallow: true
      end
    end
  end
end

app/models/attachment.rb
class Attachment < ApplicationRecord
  belongs_to :attachable, polymorphic: true, optional: true

  mount_uploader :file, FileUploader
end

app/controllers/attachments_controller.rb
class AttachmentsController < ApplicationController
  before_action :authenticate_user!

  authorize_resource

  def destroy
    @attachment = Attachment.find(params[:id])
    @attachment.destroy
  end
end

app/views/attachments/_fields.html.slim
.nested-fields
  = f.label :file
  = f.file_field :file
  = link_to_remove_association "Remove", f

app/views/attachments/_list.html.slim
h3= 'Attachments:'
ul
  - resource.attachments.each do |a|
    li class="attachment-#{a.id}"
      => link_to a.file.identifier, a.file.url
      - if can? :destroy, a
        = link_to 'Delete attachment', attachment_path(a), method: :delete, remote: true, data: {confirm: 'Are you sure?'}

app/views/attachments/destroy.js.erb
$('.attachment-<%= @attachment.id %>').remove();