config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  use_doorkeeper
  devise_for :users, controllers: { omniauth_callbacks: 'omniauth_callbacks' }
  root to: 'questions#index'

  get :search, to: 'search#index'

  concern :votable do
    member do
      patch 'set_like'
      patch 'set_dislike'
      patch 'cancel_vote'
    end
  end

  concern :commentable do
    resources :comments, only: [:create, :update, :destroy], shallow: true
  end

  resources :questions, concerns: [:votable, :commentable] do
    resources :answers, shallow: true, concerns: [:votable, :commentable], only: [:create, :update, :destroy] do
      member do
        patch :set_best
      end
    end

    resources :subscriptions, only: [:create, :destroy], shallow: true
  end

  resources :attachments, only: :destroy

  mount ActionCable.server => '/cable'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  namespace :api do
    namespace :v1 do
      resources :profiles, only: :index do
        get :me, on: :collection
      end

      resources :questions, only: [:index, :show, :create] do
        resources :answers, only: [:index, :show, :create], shallow: true
      end
    end
  end
end

app/models/answer.rb
class Answer < ApplicationRecord
  include Attachable
  include Votable
  include Commentable

  belongs_to :user
  belongs_to :question, touch: true

  validates :body, presence: true

  default_scope { order(best: :desc, created_at: :asc) }

  after_create_commit :notify_subscribers

  def set_best!
    best_answer = question.answers.find_by(best: true)

    transaction do
      best_answer.update!(best: false) if best_answer
      update!(best: true)
    end
  end

  private

  def notify_subscribers
    NewAnswerNotificationJob.perform_later(self)
  end
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  include Voted

  before_action :authenticate_user!
  before_action :find_question, only: :create
  before_action :find_answer, only: [:update, :destroy, :set_best]
  after_action :publish_answer, only: :create

  authorize_resource

  def create
    @answer = @question.answers.new(answer_params)
    @answer.user = current_user

    @answer.save
  end

  def update
    @answer.update(answer_params)
  end

  def destroy
    @answer.destroy
  end

  def set_best
    @question = @answer.question
    @answer.set_best!
  end

  private

  def find_question
    @question = Question.find(params[:question_id])
  end

  def find_answer
    @answer = Answer.find(params[:id])
  end

  def answer_params
    params.require(:answer).permit(:body, attachments_attributes: [:file, :id, :_destroy])
  end

  def publish_answer
    return if @answer.errors.any?
    ActionCable.server.broadcast(
      "answers_question_#{@question.id}",
      answer: @answer,
      attachments: @answer.attachments,
      rating: @answer.rating
    )
  end
end

app/controllers/api/v1/answers_controller.rb
class Api::V1::AnswersController < Api::V1::BaseController
  before_action :load_question, only: [:index, :create]
  before_action :load_answer, only: :show

  authorize_resource

  def index
    respond_with @question.answers
  end

  def show
    respond_with @answer
  end

  def create
    respond_with @question.answers.create(answer_params.merge(user: current_resource_owner))
  end

  private

  def load_question
    @question = Question.find(params[:question_id])
  end

  def load_answer
    @answer = Answer.find(params[:id])
  end

  def answer_params
    params.require(:answer).permit(:body)
  end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/views/answers/_answer.html.slim
- if answer.persisted?
  - cache answer do
    div class="answer_#{answer.id}"
      p= "#{answer.body}#{answer.best? ? ' (Best answer)' : ''}"

      - if answer.attachments.any?
        .answer_attachments
          = render 'attachments/list', resource: answer

      .answer_rating
        = render 'votes/rating', resource: answer

      - if can? :set_best, answer
        => link_to 'Choose as the best', set_best_answer_url(answer), method: :patch, remote: true
      - if can? :update, answer
        => link_to 'Edit', '', class: 'edit-answer-link', data: { answer_id: answer.id }
        = form_for answer, remote: true, html: { id: "edit-answer-#{answer.id}" } do |f|
          span.errors
          p= f.label :body, 'Answer'
          p= f.text_area :body
          p= f.submit 'Save'
      - if can? :destroy, answer
        = link_to 'Delete', answer_path(answer), method: :delete, remote: true, data: {confirm: 'Are you sure?'}

      .answer_comments
        - if can? :create, Comment
          => link_to 'Add comment', '', class: 'add-comment-link', data: {resource_id: answer.id, resource_type: 'answer'}
          = render 'comments/form', resource: answer
        - if answer.comments.size > 1
          h4= 'Comments:'
          = render answer.comments

app/views/answers/_form.html.slim
.answer_form
  = form_for [@question, @answer], remote: true do |f|
    span.new_answer_errors
    p= f.label :body, 'Your answer'
    p= f.text_area :body, class: 'answer_text_area'
    p Attachments:
    .attachments
      = f.fields_for :attachments, @answer.attachments.new do |a|
        = render 'attachments/fields', f: a
        = link_to_add_association 'Attach file', f, :attachments, partial: 'attachments/fields'
    p= f.submit 'Reply'

app/views/answers/create.js.erb
$('.new_answer_errors').html('<%= j render partial: 'shared/errors', locals: { model: @answer } %>');
$('.answers').append('<%= j render @answer %>');
$('.answer_text_area').val('');
$('.nested-fields').remove();

app/views/answers/destroy.js.erb
$('.answer_<%= @answer.id %>').remove();

app/views/answers/set_best.js.erb
$('.answers').html('<%= j render @question.answers %>');

app/views/answers/update.js.erb
<% if @answer&.errors.present? %>
  errors = $('form#edit-answer-<%= @answer.id %>').find('.errors');
  errors.html('<%= j render partial: 'shared/errors', locals: { model: @answer } %>');
<% else %>
  $('.answer_<%= @answer.id %>').html('<%= j render @answer %>');
<% end %>